import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import Header from "../components/headers/Desktop";
import UserInput from "../components/main/UserInput";
import { GeneratedScriptProvider } from "@/components/providers/ScriptProvider";
import Header from "@/components/headers/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} gradient-bg`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
